#!/usr/bin/env bash
# Direct-cable link to the PS4, optionally with NAT'd internet + a DNS blocklist.
#
#   ./ps4link.sh up          link only (static IP on the cable, no internet)
#   ./ps4link.sh net         link + NAT internet + PS DNS blocking  (alias: up --net)
#   ./ps4link.sh down        tear everything down, hand the port back to NM
#   ./ps4link.sh status      show what is currently active
#
# The DNS blocklist is the hosts file from https://github.com/Misl3d/PS-dns-block
# (PS4+PS5 update/telemetry domains). It is served ONLY to the console: our
# dnsmasq binds to the cable interface, so the laptop's own DNS is untouched.
# Port 53 from the console is REDIRECTed to it, so a hardcoded DNS on the PS4
# cannot bypass the block.
#
# All firewall changes live in dedicated chains (PS4LINK_*), so teardown removes
# exactly what we added and never disturbs docker/libvirt/system rules.
set -euo pipefail

IFACE="enp2s0"                    # <-- cable port to the PS4 (check: ip link)
LAN_IP="192.168.100.1"
LAN_CIDR="192.168.100.1/24"
LAN_NET="192.168.100.0/24"

BLOCKLIST_URL="https://raw.githubusercontent.com/Misl3d/PS-dns-block/main/ps-block"
STATE_DIR="/var/lib/ps4link"
BLOCK_CONF="$STATE_DIR/block.conf"
DNSMASQ_CONF="$STATE_DIR/dnsmasq.conf"
DNSMASQ_PID="$STATE_DIR/dnsmasq.pid"
FWD_PREV="$STATE_DIR/ip_forward.prev"

CH_FWD="PS4LINK_FWD"
CH_NAT="PS4LINK_NAT"
CH_DNS="PS4LINK_DNS"

if [[ $EUID -ne 0 ]]; then
  exec sudo "$0" "$@"
fi

# ---- helpers ---------------------------------------------------------------

uplink() {
  # interface carrying the default route (wifi today, may change)
  ip route show default 2>/dev/null | awk '{print $5; exit}'
}

upstream_dns() {
  # real resolvers to forward the non-blocked queries to: prefer the uplink's
  # gateway, then anything non-loopback in resolv.conf, then a public fallback.
  local gw
  gw=$(ip route show default 2>/dev/null | awk '{print $3; exit}')
  [[ -n "${gw:-}" ]] && echo "$gw"
  awk '/^nameserver/ && $2 !~ /^127\./ {print $2}' /etc/resolv.conf 2>/dev/null || true
  echo "1.1.1.1"
}

link_up() {
  nmcli device set "$IFACE" managed no || true
  ip link set "$IFACE" up
  ip addr flush dev "$IFACE"
  ip addr add "$LAN_CIDR" dev "$IFACE"
  echo "OK: $IFACE = $LAN_CIDR (unmanaged)"
}

link_down() {
  ip addr flush dev "$IFACE" 2>/dev/null || true
  nmcli device set "$IFACE" managed yes || true
  echo "OK: $IFACE returned to NetworkManager"
}

# ---- DNS (dnsmasq bound to the cable only) ---------------------------------

blocklist_refresh() {
  mkdir -p "$STATE_DIR"
  local tmp="$STATE_DIR/.ps-block.tmp"
  if curl -fsS --max-time 20 "$BLOCKLIST_URL" -o "$tmp" 2>/dev/null; then
    # hosts format: "0.0.0.0<TAB>domain" -> dnsmasq "address=/domain/0.0.0.0"
    awk '/^0\.0\.0\.0[ \t]+/ { print "address=/" $2 "/0.0.0.0" }' "$tmp" \
      | sort -u > "$BLOCK_CONF"
    rm -f "$tmp"
    echo "blocklist: $(wc -l < "$BLOCK_CONF") domains (fetched)"
  elif [[ -s "$BLOCK_CONF" ]]; then
    echo "blocklist: fetch failed, using cached $(wc -l < "$BLOCK_CONF") domains"
  else
    echo "blocklist: fetch failed and no cache — continuing with NO blocking" >&2
    : > "$BLOCK_CONF"
  fi
}

dns_up() {
  mkdir -p "$STATE_DIR"
  blocklist_refresh

  {
    echo "# generated by ps4link.sh — do not edit"
    echo "port=53"
    echo "interface=$IFACE"
    echo "bind-interfaces"          # listen ONLY here; laptop DNS untouched
    echo "listen-address=$LAN_IP"
    echo "no-resolv"
    echo "domain-needed"
    echo "bogus-priv"
    upstream_dns | awk 'NF && !seen[$0]++ { print "server=" $0 }'
    # DHCP so the console can just be left on "Automatic"
    echo "dhcp-range=192.168.100.50,192.168.100.150,12h"
    echo "dhcp-option=3,$LAN_IP"    # gateway
    echo "dhcp-option=6,$LAN_IP"    # dns
    echo "conf-file=$BLOCK_CONF"
  } > "$DNSMASQ_CONF"

  dns_down_quiet
  dnsmasq --conf-file="$DNSMASQ_CONF" --pid-file="$DNSMASQ_PID"
  echo "OK: dnsmasq on $LAN_IP ($IFACE only), blocking $(wc -l < "$BLOCK_CONF") domains"
}

dns_down_quiet() {
  if [[ -f "$DNSMASQ_PID" ]]; then
    kill "$(cat "$DNSMASQ_PID")" 2>/dev/null || true
    rm -f "$DNSMASQ_PID"
  fi
}

# ---- NAT / forwarding ------------------------------------------------------

nat_up() {
  local up
  up=$(uplink)
  if [[ -z "${up:-}" ]]; then
    echo "no default route — cannot share internet" >&2
    return 1
  fi

  mkdir -p "$STATE_DIR"
  sysctl -n net.ipv4.ip_forward > "$FWD_PREV"
  sysctl -qw net.ipv4.ip_forward=1

  # masquerade console -> uplink
  iptables -t nat -N "$CH_NAT" 2>/dev/null || true
  iptables -t nat -F "$CH_NAT"
  iptables -t nat -A "$CH_NAT" -s "$LAN_NET" -o "$up" -j MASQUERADE
  iptables -t nat -C POSTROUTING -j "$CH_NAT" 2>/dev/null \
    || iptables -t nat -I POSTROUTING 1 -j "$CH_NAT"

  # allow the forwarding both ways (inserted first so a DROP policy/docker wins nothing)
  iptables -N "$CH_FWD" 2>/dev/null || true
  iptables -F "$CH_FWD"
  iptables -A "$CH_FWD" -i "$IFACE" -o "$up" -j ACCEPT
  iptables -A "$CH_FWD" -i "$up" -o "$IFACE" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  iptables -C FORWARD -j "$CH_FWD" 2>/dev/null \
    || iptables -I FORWARD 1 -j "$CH_FWD"

  # force every console DNS query into our dnsmasq (defeats hardcoded resolvers)
  iptables -t nat -N "$CH_DNS" 2>/dev/null || true
  iptables -t nat -F "$CH_DNS"
  iptables -t nat -A "$CH_DNS" -i "$IFACE" -p udp --dport 53 -j REDIRECT --to-ports 53
  iptables -t nat -A "$CH_DNS" -i "$IFACE" -p tcp --dport 53 -j REDIRECT --to-ports 53
  iptables -t nat -C PREROUTING -j "$CH_DNS" 2>/dev/null \
    || iptables -t nat -I PREROUTING 1 -j "$CH_DNS"

  echo "OK: NAT $LAN_NET -> $up (DNS forced to $LAN_IP)"
}

nat_down() {
  iptables -t nat -D POSTROUTING -j "$CH_NAT" 2>/dev/null || true
  iptables -t nat -F "$CH_NAT" 2>/dev/null || true
  iptables -t nat -X "$CH_NAT" 2>/dev/null || true

  iptables -D FORWARD -j "$CH_FWD" 2>/dev/null || true
  iptables -F "$CH_FWD" 2>/dev/null || true
  iptables -X "$CH_FWD" 2>/dev/null || true

  iptables -t nat -D PREROUTING -j "$CH_DNS" 2>/dev/null || true
  iptables -t nat -F "$CH_DNS" 2>/dev/null || true
  iptables -t nat -X "$CH_DNS" 2>/dev/null || true

  if [[ -f "$FWD_PREV" ]]; then
    sysctl -qw net.ipv4.ip_forward="$(cat "$FWD_PREV")" || true
    rm -f "$FWD_PREV"
  fi
}

# ---- entry -----------------------------------------------------------------

MODE="${1:-up}"
[[ "${2:-}" == "--net" ]] && MODE="net"

case "$MODE" in
up)
  link_up
  ip addr show "$IFACE" | grep -w inet
  ;;

net)
  link_up
  dns_up
  nat_up
  echo
  echo "PS4 network settings: Automatic (DHCP) — or manual:"
  echo "  IP 192.168.100.2 / mask 255.255.255.0 / gateway $LAN_IP / DNS $LAN_IP"
  ;;

down)
  nat_down
  dns_down_quiet
  link_down
  ;;

status)
  echo "== link =="
  ip addr show "$IFACE" 2>/dev/null | grep -w inet || echo "  (no address)"
  echo "== dnsmasq =="
  if [[ -f "$DNSMASQ_PID" ]] && kill -0 "$(cat "$DNSMASQ_PID")" 2>/dev/null; then
    echo "  running (pid $(cat "$DNSMASQ_PID")), $(wc -l < "$BLOCK_CONF" 2>/dev/null || echo 0) domains blocked"
  else
    echo "  not running"
  fi
  echo "== firewall =="
  iptables -t nat -S "$CH_NAT" 2>/dev/null | sed 's/^/  /' || echo "  no NAT chain"
  iptables -S "$CH_FWD" 2>/dev/null | sed 's/^/  /' || echo "  no FORWARD chain"
  iptables -t nat -S "$CH_DNS" 2>/dev/null | sed 's/^/  /' || echo "  no DNS chain"
  echo "== ip_forward =="
  echo "  $(sysctl -n net.ipv4.ip_forward)"
  ;;

*)
  echo "usage: $0 [up|net|down|status]" >&2
  exit 1
  ;;
esac
